# -----------------------------
#  Base Image: Java 25 + Maven
# -----------------------------
FROM eclipse-temurin:25-jdk AS base
  
  # Install Maven
RUN apt-get update && \
apt-get install -y maven && \
apt-get clean
  
  # Set working directory
WORKDIR /automation
  
  # Copy project files
COPY . .
  
  # Ensure Maven dependencies are downloaded early (cache layer)
RUN mvn -B dependency:resolve dependency:resolve-plugins
  
  # -----------------------------
  #  Default Command
  #  (Runs smoke tests by default)
  # -----------------------------
CMD ["bash", "-c", "mvn clean test -Dcucumber.filter.tags='@smoke'"]